# Enable detailed SQL logging for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate SQL statements
logging.level.org.hibernate.SQL=DEBUG
# Hibernate 6 bind parameters
logging.level.org.hibernate.orm.jdbc.bind=TRACE
